[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

; ชี้ addons ของ source + custom addons ของคุณ
addons_path = /opt/odoo/addons,/opt/odoo/odoo/addons,/mnt/extra-addons

; (ถ้าจะ dev สะดวก)
dev = reload